name: ci

# run the workflow on every push to main branch

on:
  push:
    branches:
      - 'main'
    
# your work flow job 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to dockr hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Set up Docker Builx
        uses: docker/setup-buildx-action@v1
      -
        name: build and push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets. DOCKER_HUB_USERNAME }}/sroke_predication:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/sroke_predication:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/sroke_predication:buildcache,mode=max